### ISSUE TITLE
Support recursive asset fingerprinting

### ISSUE THREAD

**Issue by lsnape** [AdamFrey/boot-asset-fingerprint#5]
I tried to fingerprint an image URL in my stylesheet, which itself is pulled in by index.html, only to find that the fingerprinted CSS doesn't contain the fingerprinted image URL.

This is easy to reproduce by augmenting the example project slightly by changing `app.css` to:

``` css
body {
    background-image: url('${img/foo.png}');
    color: red;
}
```

And of course adding some file at `img/foo.png`. Now, in the target dir `app.css` has the fingerprinted path:

``` css
body {
    background-image: url('/img/foo-3a6b2cc87905e826f9b5e8079fc5b74e.png');
    color: red;
}
```
But the fingerprinted CSS file `app-3d31d9b4931c0cfd1054f314aa884d3b.css `, being referred to in the `index.html`, does not.

I assume that some sort of topological sort is needed to process the top level files first, and then the first level fingerprinted files, and so on. I haven't looked at the code in detail, but I'd be happy to have a stab at solving this.

Thanks!
